# Generated by Django 4.0.3 on 2022-04-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphiccards',
            name='categories',
            field=models.ManyToManyField(to='Products.products'),
        ),
    ]
