# Generated by Django 4.0.3 on 2022-04-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_graphiccards_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphiccards',
            name='categories',
        ),
    ]
