# Generated by Django 4.0.3 on 2022-04-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_graphiccards_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccards',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
