# Generated by Django 4.0.3 on 2022-04-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0004_alter_graphiccards_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphiccards',
            name='Products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.products'),
        ),
        migrations.AlterField(
            model_name='graphiccards',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
