# Generated by Django 4.0.3 on 2022-04-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_graphiccards_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphiccards',
            name='Products',
        ),
    ]
