# Generated by Django 4.0.3 on 2022-04-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_graphiccards_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphiccards',
            name='Products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.products'),
        ),
    ]
