# Generated by Django 4.0.3 on 2022-04-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_graphiccards_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
    ]
