# Generated by Django 4.0.3 on 2022-04-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_products_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccards',
            name='Products',
            field=models.ForeignKey(blank=True, default='Graphic Cards', on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
