# Generated by Django 4.0.3 on 2022-04-16 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_graphiccards_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphiccards',
            name='Products',
        ),
        migrations.AddField(
            model_name='graphiccards',
            name='products',
            field=models.OneToOneField(default='product', on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AddField(
            model_name='monitors',
            name='products',
            field=models.OneToOneField(default='product', on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
