# Generated by Django 4.0.3 on 2022-04-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_remove_graphiccards_products_graphiccards_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphiccards',
            name='products',
        ),
        migrations.RemoveField(
            model_name='monitors',
            name='products',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
