# Generated by Django 4.0.3 on 2022-04-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_remove_graphiccards_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitors',
            name='brand',
            field=models.CharField(choices=[('BenQ', 'BenQ'), ('MSI', 'MSI'), ('AOC', 'AOC'), ('Asus', 'Asus')], default='Monitors', max_length=50),
        ),
    ]
