# Generated by Django 4.0.3 on 2022-04-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_alter_monitors_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=300)),
                ('sub_products_name', models.CharField(choices=[('Graphic Cards', (('Nvidia', 'Nvidia'), ('AMD', 'AMD'))), ('Monitors', (('BenQ', 'BenQ'), ('MSI', 'MSI')))], max_length=300)),
            ],
        ),
    ]
