# Generated by Django 4.0.3 on 2022-04-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_sell_sell_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='sell_products',
        ),
    ]
