# Generated by Django 4.0.3 on 2022-04-17 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0018_remove_sell_sell_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='sub_products_name',
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_products',
            field=models.ForeignKey(default='Sell', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sell',
            name='Product_name',
            field=models.CharField(choices=[('Graphic Cards', (('Nvidia', 'Nvidia'), ('AMD', 'AMD'))), ('Monitors', (('BenQ', 'BenQ'), ('MSI', 'MSI')))], max_length=300),
        ),
    ]
