# Generated by Django 4.0.3 on 2022-04-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_remove_sell_sub_products_name_sell_sell_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='sell_products',
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_products_cards',
            field=models.OneToOneField(default='Sell', on_delete=django.db.models.deletion.CASCADE, to='Products.graphiccards'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='Product_name',
            field=models.CharField(choices=[('Graphic Cards', (('Nvidia', 'Nvidia'), ('AMD', 'AMD'))), ('Monitors', (('BenQ', 'BenQ'), ('MSI', 'MSI')))], default='Sell', max_length=300),
        ),
    ]
