# Generated by Django 4.0.3 on 2022-04-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_alter_sell_sell_products_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='Product_Type',
            field=models.CharField(choices=[('Nvidia', (('RTX', 'RTX'), ('GTX', 'GTX'))), ('AMD', (('RX', 'RX'), ('6000Series', '6000Series')))], default='Sell', max_length=300),
        ),
    ]
