# Generated by Django 4.0.3 on 2022-04-17 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0022_sell_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sell_products_cards',
            field=models.ForeignKey(default='Sell', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
