# Generated by Django 4.0.3 on 2022-04-17 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_sell_description_alter_sell_sell_products_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='sell_products_cards',
            new_name='author',
        ),
    ]
