# Generated by Django 4.0.3 on 2022-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoJS', '0002_produit_serie_alter_produit_choix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='serie',
            field=models.CharField(choices=[('Rtx 3060ti', 'Rtx 3060ti'), ('5700xt', '5700xt'), ('A380', 'A380')], max_length=12),
        ),
    ]
