# Generated by Django 4.0.3 on 2022-03-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_products_p_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_author',
        ),
    ]
