# Generated by Django 4.0.3 on 2022-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_products_p_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_image',
            field=models.ImageField(default='default.jpg', upload_to='products_pics'),
        ),
    ]
