# Generated by Django 4.0.3 on 2022-04-06 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_products_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=35)),
                ('p_descript', models.TextField(max_length=200)),
                ('p_image', models.ImageField(default='default.jpg', upload_to='graphiccards_pics')),
                ('p_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_brand', models.CharField(max_length=20)),
                ('m_descript', models.TextField(max_length=200)),
                ('m_image', models.ImageField(default='default.jpg', upload_to='monitors_pics')),
                ('m_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
