# Generated by Django 4.0.3 on 2022-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_graphiccards_date_posted_monitors_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphiccards',
            name='brand',
            field=models.CharField(choices=[('Nvidia', 'Nvidia'), ('AMD', 'AMD'), ('Intel', 'Intel')], max_length=50, null=True),
        ),
    ]
