# Generated by Django 4.0.3 on 2022-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_graphiccards_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccards',
            name='brand',
            field=models.CharField(choices=[('Nvidia', 'Nvidia'), ('AMD', 'AMD'), ('Intel', 'Intel')], default='GrahicCard', max_length=50),
        ),
    ]
