# Generated by Django 4.0.3 on 2022-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_graphiccards_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccards',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
