# Generated by Django 4.0.3 on 2022-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_graphiccards_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphiccards',
            name='prce',
            field=models.IntegerField(default=0),
        ),
    ]
